[default]
description = "Default permissions for custom commands"
permissions = ["allow-take-screenshot", "allow-open-fullscreen-viewer", "allow-get-skills-data", "allow-open-skill-graph-viewer"]

[[permission]]
identifier = "allow-take-screenshot"
description = "Allows the take_screenshot command"

[permission.commands]
allow = ["take_screenshot"]
deny = []

[[permission]]
identifier = "allow-open-fullscreen-viewer"
description = "Allows the open_fullscreen_viewer command"

[permission.commands]
allow = ["open_fullscreen_viewer"]
deny = []

[[permission]]
identifier = "allow-get-skills-data"
description = "Allows the get_skills_data command"

[permission.commands]
allow = ["get_skills_data"]
deny = []

[[permission]]
identifier = "allow-open-skill-graph-viewer"
description = "Allows the open_skill_graph_viewer command"

[permission.commands]
allow = ["open_skill_graph_viewer"]
deny = []
